### ISSUE TITLE
cant find image

### ISSUE THREAD

**Issue by apn4fighter** [ollama-webui/ollama-webui#103]
Hi All

I wanted to try it with the command docker run -d -p 3000:8080 --name ollama-webui:latest --restart always ollama-webui
but then this happens

Unable to find image 'ollama-webui:latest' locally
docker: Error response from daemon: pull access denied for ollama-webui, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'

**Comment by tjbck** [comment]
Hi, it looks like you were encountering the issue because you didn't have the container image built.

As per the instruction in README.md (https://github.com/ollama-webui/ollama-webui#using-docker-), the following should've been the commands to **build** and **run** the container:

```
docker build --build-arg OLLAMA_API_BASE_URL='' -t ollama-webui .
docker run -d -p 3000:8080 --name ollama-webui --restart always ollama-webui
```

and **NOT** this:

```
docker run -d -p 3000:8080 --name ollama-webui:latest --restart always ollama-webui
```

In addition, 'ollamawebui/ollama-webui' has been **deprecated** and pulling the prebuilt container image from 'ghcr.io/ollama-webui/ollama-webui:main' is **recommended**, which will have the most up-to-date features by default.

If you have any other questions, don't hesitate to reach out. Thanks!
