### ISSUE TITLE
Make copying text easier while text is still generated

### ISSUE THREAD

**Issue by tosh** [ollama-webui/ollama-webui#119]
**Describe the bug**
If you try to copy text while text is still generated the selection gets reset/lost (because the view gets re-rendered?)

**To Reproduce**
1. send a message
2. output starts to show token by token
3. select text in the output to copy
4. selected text gets deselected when the next token gets output

**Expected behavior**
text selection stays stable/selected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari 17.1, Chrome 119

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion. I'll have to look into this but I believe this is due to how svelte manipulates the DOM directly. Unfortunately I'm currently overwhelmed with all the work, so I'll take a look whenever I can. If you manage to find out a solution in the meantime, please reply to this thread or PR is always welcome!
