### ISSUE TITLE
feat: customizable profile picture and name

### ISSUE THREAD

**Issue by mak448a** [ollama-webui/ollama-webui#235]
**Is your feature request related to a problem? Please describe.**
It would be nice to have it say something else other than ollama.

**Describe the solution you'd like**
Provide a way to change the picture and name of the bot.

**Comment by tjbck** [comment]
Hi, you can already customize the ui using the modelfile builder feature, but I'll take a look if time allows it, stay tuned.

**Comment by mak448a** [comment]
That's exactly what I wanted. Thanks!

**Comment by smileBeda** [comment]
@tjbck, can I ask what you mean with 
> Hi, you can already customize the ui using the modelfile builder feature, but I'll take a look if time allows it, stay tuned.

I can only see "use gravatar" or "use initials" when customizing the user profile picture.
I recently stepped away from gravatar due to some serious concerns the OSS community should have in regards to that service, and would like to upload my own image.

How can this be achieved?
Thank you!
