### ISSUE TITLE
How do you set/load the first default model as default?

### ISSUE THREAD

**Issue by oliverbob** [ollama-webui/ollama-webui#266]
When the UI loads, users expect to be able to chat directly (just like in Chat GPT), coz it is annoying to receive a "Model not selected" message on first impression chat experience.

What file will I need to modify to preselect orca-mini:3b for instance?

Can it be modefied in ModelSelector.svelte?

I tried <option class=" text-gray-700" value="orca-mini:3b" selected>Select a model</option>

But this only adds it to the list and still have to be selected.

Your help is appreciated.

**Comment by justinh-rahb** [comment]
I think it'd be a useful feature to be able to set a default model with environment variable. Would that suffice to solve this for you?

**Comment by oliverbob** [comment]
> I think it'd be a useful feature to be able to set a default model with environment variable. Would that suffice to solve this for you?

Yes, whatever we can do to solve it. It is not for ourselves by the way, but for the end users of this great UI.

**Comment by tjbck** [comment]
Hi, I'll think of a way to implement it but if anyone manages to implement this in the meantime, feel free to make a PR!

One workaround for this would be setting the models url search param like such: `http://localhost:3000/?models=mistral:latest` Thanks!

**Comment by oliverbob** [comment]
> Hi, I'll think of a way to implement it but if anyone manages to implement this in the meantime, feel free to make a PR!
> 
> One workaround for this would be setting the models url search param like such: `http://localhost:3000/?models=mistral:latest` Thanks!

Its difficult to make it work as a default home reverse proxy in Apache. Since it doesnt allow queiries without special instructions/directives.

Given such URL as built in feature, we can create a JavaScript or PHP redirect. Im sure that's possible in the backend but Im new to Svelte. I Just researched it last night 🤔😁 That is why I can contribute or make modifications less likely.

But I appreciate your prompt response. 🖖

**Comment by tjbck** [comment]
Hi all, I've been thinking about what would be the best way to implement this without adding extra layer of complexity, and decided that it would be best if admin's default models is set globally, which is what I ended up implementing. Just merged a branch with the feature, Please try out the latest version and let me know if you encounter any issues, Thanks!

**Comment by justinh-rahb** [comment]
This is an elegant enough solution, will try it out ASAP.

**Comment by justinh-rahb** [comment]
@tjbck seems to work great on my end 👌

**Comment by jeannotdamoiseaux** [comment]
I found the process of setting a default model for users as an admin to be unintuitive. I expected a more straightforward approach, such as a "default model" toggle or a ranking system to automatically determine the default model for users.

In the admin settings (via Settings → Models → Settings in the top-right), I noticed the options to reorder models at the top and add default models at the bottom. However, the behavior of this functionality isn’t entirely clear to me.

Does this mean that the highest-ranked default model is automatically selected for the user? What happens if no default models are selected at all?

Clarification on this process, or an update to the documentation, would be helpful.
