### ISSUE TITLE
The /api/tags route doesn't load

### ISSUE THREAD

**Issue by horiacristescu** [ollama-webui/ollama-webui#28]
**Describe the bug**

The model list remains empty. When I look into the network tab, I see the /api/tags route fails

http://myhost:11434/api/tags
Failed to load resource: net::ERR_CONNECTION_REFUSED

However, the error doesn't always appear:
- When loading the page from localhost on Ubuntu with Chrome, it works
- When loading by IP address on macbook, it fails in all 3 browsers (Chrome, FF, Edge). It even fails with VS Code port forwarding, loading as http://0.0.0.0:3000/ on Mac.

**To Reproduce**
1. Load thee root page
2. The model list is empty

**Expected behavior**
Model list should load from all browsers and loaded on 0.0.0.0 or IP

I tried
```
docker build --build-arg PUBLIC_API_BASE_URL='http://192.168.0.185:11434/api' --build-arg OLLAMA_API_BASE_URL='http://192.168.0.185:11434/api' -t ollama-webui .
```

and

```
docker build --build-arg OLLAMA_API_BASE_URL='http://192.168.0.185:11434/api' -t ollama-webui .
```

**Comment by tjbck** [comment]
Hi, It's most likely caused by a CORS error, make sure to run the following command to serve Ollama, as mentioned [here](https://github.com/ollama-webui/ollama-webui#accessing-ollama-web-interface-over-lan), which should solve your issue:

```sh
OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* ollama serve
```

Keep me updated, Thanks.

**Comment by awptechnologies** [comment]
same thing for me. Also to even get web page to load i had to map port to 3000 inside to container instead of the 8080 in the read me. 

to build image i coppied the latest release to my host. ran docker build inside the ollama folder. 

image build was successful but when the page loaded the model list was empty. 

I am able to interact with the model fine through the cli.

**Comment by tjbck** [comment]
@awptechnologies Hi, the latest release isn't up to date yet, please clone the repo and build from there instead. Regarding the connection error, the environment variable must be passed to Ollama itself, not the WebUI. Thanks.

**Comment by tjbck** [comment]
https://github.com/ollama-webui/ollama-webui#accessing-ollama-web-interface-over-lan

**Comment by awptechnologies** [comment]
Kinda new to github. I know how to use git but what is the link for the repository. Where do I clone into.

**Comment by awptechnologies** [comment]
figured it out. Github is the bomb. This worked perfectly. It also fixed the webpage being hosted at 8080. Love the project. Any idea when it will be able to use the internet. Awesome feeling having these resources locally. Im at the point where im done with all this big businesses.

**Comment by awptechnologies** [comment]
now my question. I have it all working perfect. I use haproxy as reverse proxy and when i try and set up the web ui to use my domain and ssl certs server connection fails. Any ideas? is there a setting i need to have for this to work??

**Comment by tjbck** [comment]
@awptechnologies  Hmm, I'm not so sure. In theory, there shouldn't be any issues caused by the Web UI. Keep us updated if you find a solution. Thanks.

**Comment by awptechnologies** [comment]
@tjbck So... I have gotten it to work.. I technically don't like the way i did it though.  So the way i did it. I set up the webUI with reverse proxy set server and port and used ollama.mydomain.com to access it. This like mentioned before left the error of not being able to connect to server. i had to then set up a reverse proxy for the API as well. So again set server and port 11434 for API, and used ollamaapi.mydomain.com. Once i did this and set the ollamaapi.mydomain.com as server for webgui it works. The reason i don't like this is because i wanted to set this up with cloudflare so i can access it publicly.  with having to do it this way i had to also expose the API. Best way i can describe it is it is using the front end of the web page to contact the server instead of going through the backend. The ideal setup would be to leave the API accessible only on private network and expose only the web GUI. When setting up cloud-flare i tried to only expose the web GUI and doing this led to the error. The only way i could get it to work is expose the API publicly as well.... Any ideas?

**Comment by awptechnologies** [comment]
i am running this in docker swarm and they are together in a stack so technically they are directly connected to each other. I figured they would be able to communicate regardless of how i access it on the front end...

**Comment by awptechnologies** [comment]
when you go to ollama.mydomain.com it only shows ollama is running. so i don't think there is any way for bad actors to mess with it just don't like the idea of the backend being accessible from anyone that knows domain.

**Comment by tjbck** [comment]
Maybe you could try @coolaj86's method of running the Web UI. I'm not so sure about how to fix your problem.
