### ISSUE TITLE
Disable authenticaton

### ISSUE THREAD

**Issue by dezoito** [ollama-webui/ollama-webui#430]
Is there a way to disable the authentication requirement, so that users don't have to login to use the UI?
Maybe having the admin user authenticating once and then disabling it?

If this entailed chats not being saved that would be alright too.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion! For security reasons, we do not plan on adding an option to remove the login feature in the near future, so I'll close this issue as not planned for now. However, https://github.com/ollama-webui/ollama-webui-lite provides with the option to use the webui without any of the additional backend functionalities (including auth)!

**Comment by sammcj** [comment]
@tjbck I think this is still needed as an option.

A good example of where Ollama Web UI authentication needs to be disabled is when you're already running the application runs behind another internal authentication service such as [Authentik](https://github.com/goauthentik/authentik) / Okta etc...

This is what I (and a few others I know) do with all our apps for a secure and unified approach but with Ollama Web UI this means logging in twice with two sets of credentials - one of which is no centrally managed.

**Comment by justinh-rahb** [comment]
How will you have chat histories and settings then? This method would need a way to pass some sort of authentication header so that WebUI knows which user to log into.

**Comment by sammcj** [comment]
In my case like I suspect a lot of self-hosters, I just have a single user.

However the standard approach with OAuth2/OpenID (which includes things like Google Workspaces, AzureAD, Authentik, Okta, Auth0 etc...) is to pass an identity token / URL / header to applications after successful authentication. You can also have it redirect to a specific URL path (e.g. <url>/users/<cool@lol.com>) etc...

**Comment by sammcj** [comment]
- https://goauthentik.io/docs/providers/proxy/header_authentication
- https://goauthentik.io/docs/providers/proxy/custom_headers

**Comment by Chukarslan** [comment]
Hi, can you detail the steps to disable auth please?

**Comment by sammcj** [comment]
Yeah this is really needed, unfortunately this issue remains closed :(

**Comment by tjbck** [comment]
The exact same issue is open here: #929

Again, we want to emphasise that this is a community project, we encourage you to make a PR!

**Comment by sammcj** [comment]
maybe something like https://github.com/open-webui/open-webui/compare/main...sammcj:open-webui:main

**Comment by Chukarslan** [comment]
This is really cool, I'll check it out thanks @sammcj!

**Comment by Chukarslan** [comment]
Update @sammcj : Still showing the /auth page :(
I tired removing the route in layout.svelte but it keeps bouncing back to auth...

**Comment by markg85** [comment]
Ohh security... for f**** sake...

Yes, i get why a login is good for security measures.

But it makes zero sense when running it as a self-hosted service with the intent to just freaking play with ollama.
Somehow so many projects just force down the authentication option where it's clearly intended to be run local for just 1 user (like portainer and grafana, to name a few). And somehow giving the option to disable it is more difficult then to implement an authentication system...

Yeah, that's fucked up.
The intent of this whole project is to **run locally** so authentication has no place in that.

Sorry for the rant. I'm just annoyed by local projects adding authentication because some people whine about that being "secure and a must-have feature" just to be a pain in the ass for everyone else running it locally as single user, like 99% of your users will!

**Comment by justinh-rahb** [comment]
> Blah blah blah yadda yadda yadda

@markg85: https://github.com/ollama-webui/ollama-webui-lite
