### ISSUE TITLE
feat: web content pipeline for rag 

### ISSUE THREAD

**Issue by tjbck** [ollama-webui/ollama-webui#464]
https://www.reddit.com/r/LocalLLaMA/comments/192dz3r/q_is_it_possible_to_give_ollama_access_to_a_local/

**Comment by justinh-rahb** [comment]
Integrating a feature in Ollama WebUI that allows users to provide a URL and have it automatically processed through RAG would be an exciting addition. However, determining how to trigger this feature raises some questions. For instance, we wouldn't want every URL mentioned in the chat to automatically trigger the RAG process since that could lead to unnecessary processing and potentially unwanted results.

One solution could be adding a button that explicitly triggers the RAG process for a given URL. However, it would be ideal if we could make this feature as automatic as possible while maintaining control over when it's triggered. One way to achieve this could be by implementing some sort of semantic routing model that recognizes specific commands or keywords in the chat input and automatically triggers the RAG process for a provided URL.

For example, if a user types "Read this article" followed by a URL, Ollama WebUI could automatically recognize the command and trigger the RAG process without requiring any additional steps. This approach would maintain the clean interface we currently have.

Here's some further information on Semantic Routing:
[YouTube](https://www.youtube.com/watch?v=ro312jDqAh0)
[Jupyter notebook](https://github.com/aurelio-labs/semantic-router/blob/main/docs/00-introduction.ipynb)
[Repo](https://github.com/aurelio-labs/semantic-router/)

OpenAI must be implementing a similar concept in ChatGPT Plus to figure out whether to generate images or code or what have you, as it wouldn't be feasible or cost-effective to require two API calls for every message, one with GPT-3.5 to determine what to use and another to perform the action with GPT-4/DALLE-3/CodeInterpreter. Therefore, implementing a semantic routing model in Ollama WebUI that recognizes specific commands and triggers the RAG process accordingly would likely provide significant benefits for users while maintaining an intuitive and uncluttered interface.

**Comment by RLutsch** [comment]
how about adding an endpoint you can publish data to? something like 
``` curl -X post <myUrl.com>/rag --data 'my.csv' ```
then option to add chromaDB?
Maybe also support for external db?

**Comment by ChingWeiChan** [comment]
Additional information about web content pipeline, I think we can integrate search api for RAG. Like [serpapi](https://serpapi.com)(free plan is 100 times search/month), [Wikipedia api](https://api.wikimedia.org/wiki/Searching_for_Wikipedia_articles_using_Python) or other.

**Comment by Marclass** [comment]
> how about adding an endpoint you can publish data to? something like `curl -X post <myUrl.com>/rag --data 'my.csv'` then option to add chromaDB? Maybe also support for external db?

The RAG endpoint to scrape web pages was added in #333 with /web.

**Comment by oliverbob** [comment]
Any update to this yet?

Thanks.

**Comment by tjbck** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/7f511461-f0f7-4784-bcb7-4297ab1210cb)

You can now add website content to rag pipeline directly using '#' command followed by the website url, let me know if you guys encounter any issues!

As for the API integration support, let's continue our discussion here: #586, Thanks!

**Comment by oliverbob** [comment]
> ![image](https://private-user-images.githubusercontent.com/25473318/300159751-7f511461-f0f7-4784-bcb7-4297ab1210cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTU0MzAsIm5iZiI6MTcwNjQ1NTEzMCwicGF0aCI6Ii8yNTQ3MzMxOC8zMDAxNTk3NTEtN2Y1MTE0NjEtZjBmNy00Nzg0LWJjYjctNDI5N2FiMTIxMGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE1MTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYWMwZWUyNjMxZGU2MTZjNWE2OTU4YjFjYTA5NGYwNTEzM2UwNjM5OTQ2MGI4MDg2NTg1MGM4YWNiNDA1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c0PhpkjEO07VjleCbTEdH5G2CxYtYZl5RbteBAB9MRY)
> 
> You can now add website content to rag pipeline directly using '#' command followed by the website url, let me know if you guys encounter any issues!
> 
> As for the API integration support, let's continue our discussion here: #586, Thanks!

Thanks mate. Been waiting for this. Will try the latest update.

**Comment by justinh-rahb** [comment]
Working great for me 💯  Congrats @tjbck for landing this absolutely huge feature!

<img width="779" alt="Screenshot 2024-01-28 at 10 07 14 AM" src="https://github.com/ollama-webui/ollama-webui/assets/52832301/06672288-8bc8-46e1-bf42-cf21f712d4ae">
