### ISSUE TITLE
feat: Create Collections of Document Files

### ISSUE THREAD

**Issue by davidamacey** [ollama-webui/ollama-webui#531]
**Is your feature request related to a problem? Please describe.**
I would like the ability to select multiple documents without having to select each file individually.

**Describe the solution you'd like**
I would like a feature that allows for the documents to be grouped by user defined collections.

For example, I have the following folders, Personal, Work, Taxes, News, Journals.  Each of those folders has numerous pdf files, but I don't want to have to select them individual or worse mix topics accidentally.

**Describe alternatives you've considered**
Add database and UI features to group document files by a named category.  Then allow the user to select a file or collection from the chat box to query against.

**Additional context**
Great work on this project!

**Comment by jnkstr** [comment]
For this a citation feature (Like in AnythingLLM) would be helpful as you are looking for collections of docs. 

You could show the name of the doc and the chunks of text received from the chromadb after sending your question in the ui as a citation.

**Comment by tjbck** [comment]
![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/4f91e8c9-2f32-448b-a67a-16482342aedf)

You can now tag documents to create document collections, let me know if you encounter any issues! 

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/0b856b49-8ddf-48d1-8b11-1052e4a0cc95)

**Comment by davidamacey** [comment]
@tjbck This looks great, thank you for doing all the backend to support this feature!

Testing chat with the documents: individual, tagged, and all documents, appear to work as intended!  This is great!

### Question:
Asking for clarification about the UI.  I am adding tags to a document, but the new tag now appears above all the documents.  It kind of looks confusing.

Not sure if I missed something on the UI.

![image](https://github.com/ollama-webui/ollama-webui/assets/6076456/c6ea7f27-9b9b-46ff-9222-9fe7046a62ee)

For testing I did the following:  #gov for Declaration, #research for attention paper #programming for sveltetxt  

Is it possible the tags are not filtering when querying from the backend to the frontend?

**Comment by tjbck** [comment]
@davidamacey Good catch! #646 fixes it!

**Comment by davidamacey** [comment]
@tjbck Thanks for your hard work and quick responses!

I hope you do not think I am nit-picking.  I am here to assist where I can.  Hopefully I can support with a PR or a feature when you need an extra dev.

**Comment by tjbck** [comment]
No worries, appreciate the feedback!

**Comment by DocMAX** [comment]
Please add feature to add EXISTING document folders from disk (no upload!)

**Comment by KelvinDenhoff** [comment]
Hey there, 

i am trying to create a collection called 'Data-Center' and want to make 2 documents part of this collection. However the issue i am facing is that whenever i try to give the same tag to multiple documents, it gives me an error. Details below:-

Here i upload the first document and give it the tag 'Data Center' and then save it.
![image](https://github.com/user-attachments/assets/aa25fba9-c7fb-4ba7-be4f-ed0b371ea675)

The UI overrides the given tag and saves it with name of the file, instead of the give tag name (ie, Data-Center)

I then upload another document and it does the exact same thing.
![image](https://github.com/user-attachments/assets/886d76da-2f2a-46d7-aecf-e0508d353a51)

Afterwards, when i try to edit both files and rename the tag to 'Data-Center' it allows me to do so for the first file, as shown below:
![image](https://github.com/user-attachments/assets/e6802fb1-3fad-4e56-8be8-013b29010a78)

However, when i try to edit the other document and give it the same tag (ie, Data-Center), it give me the following error:
![image](https://github.com/user-attachments/assets/5a7959df-7633-4516-8161-0834e23d8071)

Now this error is preventing me from creating a collection.

Help is requested please.

**Comment by KelvinDenhoff** [comment]
The above issue was resolved by updating to the latest version of open webui.
